export const SET_CONVERSIONS = "SET_CONVERSIONS";
export const AMOUNT_CHANGE = "AMOUNT_CHANGE";
export const CURRENCY_CHANGE = "CURRENCY_CHANGE";
export const CONVERT_CURRENCY = "CONVERT_CURRENCY";
export const FETCH_CONVERSIONS = "FETCH_CONVERSIONS";
export const FETCH_CONVERSIONS_ERROR = "FETCH_CONVERSIONS_ERROR";